[package]
name = "agilent-converter"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "agilent-converter"
path = "src/main.rs"

[dependencies]
catplus-common = { version="0.1.0", path = "../catplus-common"}