name: Build and Push Docker Image

on:
  release:
    types: [published]
  push:
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up just
        uses: extractions/setup-just@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build image
        run: |
          just nix::develop just image build

      - name: Push image
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          just nix::develop bash -c '
            echo "$GITHUB_TOKEN" | skopeo login ghcr.io -u $GITHUB_ACTOR --password-stdin
            just image push
          '
