name: format
on:
  pull_request:
  push:
    branches: main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v15
        with:
          name: "${{ secrets.CACHIX_CACHE_NAME }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: check code formatting
        run: |
          nix develop \
            ./tools/nix#default \
            --accept-flake-config \
            --command bash -c "just fmt --check"
